version: '3.6'

services:
 flask_app:
  build: .
  image: eldadtzabari/wog_scores_flask
  ports:
    - "8888:5555"
  volumes:
   - ./Scores.txt:/app/Scores.txt

  environment:
   - FLASK_APP=MainScores.py
   - FLASK_RUN_HOST=0.0.0.0
  command: ["flask", "run"]
